# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

flutter_application_path = '../flutter_module/'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'flutter_ios_navative' do
  install_all_flutter_pods(flutter_application_path)
  
  
  pod 'AFNetworking'

  
end
